# Generated by Django 5.2.9 on 2026-01-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0002_profile_grade_profile_school_profile_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='school',
            new_name='studying_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(blank=True, choices=[('10th', '10th'), ('12th', '12th'), ('College', 'College')], max_length=50, null=True),
        ),
    ]
