# Generated by Django 5.2.9 on 2026-01-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0003_rename_school_profile_studying_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
