# Generated by Django 5.2.9 on 2026-01-02 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0005_alter_quiz_status_adminprofile_studentprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
