# Generated by Django 5.2.9 on 2026-01-02 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0006_quiz_quiz_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizmaker.adminprofile'),
        ),
    ]
