# Generated by Django 5.2.9 on 2026-01-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0009_alter_quiz_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='created_by',
            new_name='creator',
        ),
    ]
