# Generated by Django 5.2.9 on 2026-01-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0010_rename_created_by_quiz_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='creator',
            new_name='created_by',
        ),
    ]
