# Generated by Django 5.2.9 on 2026-01-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0011_rename_creator_quiz_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='admin_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
