# Generated by Django 5.2.9 on 2026-01-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0012_adminprofile_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='admin_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
