# Generated by Django 5.2.9 on 2026-01-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0014_remove_studentprofile_user_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_for',
            field=models.CharField(blank=True, choices=[('10th', '10th'), ('12th', '12th'), ('college', 'College')], max_length=255, null=True),
        ),
    ]
