# Generated by Django 5.2.9 on 2026-01-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0016_question_marks_alter_quizattempt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='score',
        ),
    ]
