# Generated by Django 5.2.9 on 2026-01-15 13:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0017_remove_quizattempt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
