# Generated by Django 5.2.9 on 2026-01-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0019_remove_quiz_quiz_date_quiz_end_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
