# Generated by Django 5.2.9 on 2026-01-18 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0020_alter_answer_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempt', to='quizmaker.quiz'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='result',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
