# Generated by Django 5.2.9 on 2026-01-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0022_alter_quiz_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='status',
        ),
    ]
