# Generated by Django 5.2.9 on 2026-01-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0023_remove_quiz_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
