# Generated by Django 5.2.9 on 2026-01-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0024_rename_create_at_userprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_for',
            field=models.CharField(blank=True, choices=[('10th', '10th'), ('12th', '12th'), ('College', 'College')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(blank=True, choices=[('10th', '10th'), ('12th', '12th'), ('College', 'College')], max_length=50, null=True),
        ),
    ]
