# Generated by Django 5.2.9 on 2026-01-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0025_alter_quiz_quiz_for_alter_userprofile_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
