# Generated by Django 5.2.9 on 2026-01-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0026_alter_quizattempt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_for',
            field=models.CharField(blank=True, choices=[('10th', '10th'), ('12th', '12th'), ('college', 'College')], max_length=255, null=True),
        ),
    ]
