# Generated by Django 5.2.9 on 2026-06-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmaker', '0027_alter_quiz_quiz_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_for',
            field=models.CharField(blank=True, choices=[('10th', '10th'), ('12th', '12th'), ('College', 'College')], max_length=255, null=True),
        ),
    ]
